services:
  llama-cpp-server:
    environment:
      - LLAMA_CTX_SIZE=4096
      - LLAMA_N_THREADS=18
      - LLAMA_N_BATCH=512
    deploy:
      resources:
        limits:
          cpus: '18'
          memory: 28G